<a href="https://colab.research.google.com/github/KouFkaS7/PracticeWithPandas/blob/main/Reading_filtering_ordering_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
# Reading files in pandas whatever type excel csv ...
df=  pd.read_csv('/content/countries of the world.csv')
df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [ ]:
df.shape

(227, 2)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  227 non-null    object
 1   Region   227 non-null    object
dtypes: object(2)
memory usage: 3.7+ KB

In [ ]:
df.head() #first 5 values

           Country                               Region
0     Afghanistan         ASIA (EX. NEAR EAST)
1         Albania   EASTERN EUROPE
2         Algeria   NORTHERN AFRICA
3  American Samoa   OCEANIA
4         Andorra   WESTERN EUROPE

In [ ]:
#Filtering Ordering

df2 = pd.read_csv('/content/world_population.csv')
df2

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El AaiÃºn,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [ ]:
df2[df2['Country']=='Greece'] # Find specific  country's name

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
77,90,GRC,Greece,Athens,Europe,10384971.0,10512232.0,10806641.0,11033783.0,11038109.0,10302255.0,9307148.0,8544873.0,131990.0,78.68,0.9942,0.13

In [ ]:
gr_ger = ['Greece','Germany'] # I specify these countries in a list and try to find if include in df2 with isin() function

df2[df2['Country'].isin(gr_ger)]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
74,19,DEU,Germany,Berlin,Europe,83369843.0,83328988.0,82073226.0,81325090.0,81551677.0,79370196.0,77786703.0,78294583.0,357114.0,233.4544,0.9995,1.05
77,90,GRC,Greece,Athens,Europe,10384971.0,10512232.0,10806641.0,11033783.0,11038109.0,10302255.0,9307148.0,8544873.0,131990.0,78.6800,0.9942,0.13

In [ ]:
df2[df2['Country'].str.contains('United')]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
219,97,ARE,United Arab Emirates,Abu Dhabi,Asia,9441129.0,9287289.0,8916899.0,8481771.0,3275333.0,1900151.0,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
220,21,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
221,3,USA,United States,"Washington, D.C.",North America,338289857.0,335942003.0,324607776.0,311182845.0,282398554.0,248083732.0,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
222,200,VIR,United States Virgin Islands,Charlotte Amalie,North America,99465.0,100442.0,102803.0,106142.0,108185.0,100685.0,96640.0,63446.0,347.0,286.6427,0.9937,0.00

In [ ]:
df2[df2['Country'].str.contains('To')]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
181,187,STP,Sao Tome and Principe,SÃ£o TomÃ©,Africa,227380.0,218641.0,201124.0,182138.0,143714.0,120343.0,97210.0,77583.0,964.0,235.8714,1.0192,0.00
208,100,TGO,Togo,LomÃ©,Africa,8848699.0,8442580.0,7473229.0,6571855.0,5008035.0,3875947.0,2838110.0,2197383.0,56785.0,155.8281,1.0236,0.11
209,233,TKL,Tokelau,Nukunonu,Oceania,1871.0,1827.0,1454.0,1367.0,1666.0,1669.0,1647.0,1714.0,12.0,155.9167,1.0119,0.00
210,197,TON,Tonga,Nukuâ€˜alofa,Oceania,106858.0,105254.0,106122.0,107383.0,102603.0,98727.0,96708.0,86484.0,747.0,143.0495,1.0079,0.00
211,153,TTO,Trinidad and Tobago,Port-of-Spain,North America,1531044.0,1518147.0,1460177.0,1410296.0,1332203.0,1266518.0,1127852.0,988890.0,5130.0,NaN,1.0035,0.02

In [ ]:
df3 = df2.set_index('Country')
df3

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El AaiÃºn,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [ ]:
df3.filter(items = ['CCA3','Continent']) # axes can be 0 or 1 horizontal or defeault

                  CCA3 Continent
Country
Afghanistan        AFG      Asia
Albania            ALB    Europe
Algeria            DZA    Africa
American Samoa     ASM   Oceania
Andorra            AND    Europe
...                ...       ...
Wallis and Futuna  WLF   Oceania
Western Sahara     ESH    Africa
Yemen              YEM      Asia
Zambia             ZMB    Africa
Zimbabwe           ZWE    Africa

[234 rows x 2 columns]

In [ ]:
df3.filter(items = ['Greece'],axis=0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Greece,90,GRC,Athens,Europe,10384971.0,10512232.0,10806641.0,11033783.0,11038109.0,10302255.0,9307148.0,8544873.0,131990.0,78.68,0.9942,0.13

In [ ]:
df3.filter(like ='Greece',axis=0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Greece,90,GRC,Athens,Europe,10384971.0,10512232.0,10806641.0,11033783.0,11038109.0,10302255.0,9307148.0,8544873.0,131990.0,78.68,0.9942,0.13

In [ ]:
df3.loc['Greece']

Rank                                   90
CCA3                                  GRC
Capital                            Athens
Continent                          Europe
2022 Population                10384971.0
2020 Population                10512232.0
2015 Population                10806641.0
2010 Population                11033783.0
2000 Population                11038109.0
1990 Population                10302255.0
1980 Population                 9307148.0
1970 Population                 8544873.0
Area (kmÂ²)                       131990.0
Density (per kmÂ²)                   78.68
Growth Rate                        0.9942
World Population Percentage          0.13
Name: Greece, dtype: object

In [ ]:
df3.iloc[90]

Rank                                   94
CCA3                                  HUN
Capital                          Budapest
Continent                          Europe
2022 Population                 9967308.0
2020 Population                 9750573.0
2015 Population                 9844246.0
2010 Population                 9986825.0
2000 Population                10202055.0
1990 Population                       NaN
1980 Population                       NaN
1970 Population                10315366.0
Area (kmÂ²)                        93028.0
Density (per kmÂ²)                107.1431
Growth Rate                        1.0265
World Population Percentage          0.12
Name: Hungary, dtype: object

In [ ]:
df2[df2['Rank'] <=5].sort_values(by=['Capital','Continent'])

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24